# This site is served by GitHub Pages.
# This document is only for the PRs and branch deploys on Netlify.

[build]
  publish = "public"
  command = "hugo --minify -b $URL"

[build.environment]
  HUGO_VERSION = "0.147.0"

[context.deploy-preview]
  command = "hugo --minify -b $DEPLOY_PRIME_URL"

[context.branch-deploy]
  command = "hugo --minify -b $DEPLOY_PRIME_URL"